version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
artifacts:
  files:
    -- src/**/*
    -- package.json